name: guruku_student
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  midtrans_snap: ^1.0.1
  webview_flutter: ^4.8.0
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  http: ^1.2.1
  get_it: ^7.6.7
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  animated_text_kit: ^4.2.2
  dartz: ^0.10.1
  shared_preferences: ^2.2.2
  sqflite: ^2.3.3+1
  awesome_dialog: ^3.2.0
  google_fonts: ^6.2.1
  restart_app: ^1.2.1
  flutter_svg: ^2.0.10+1
  carousel_slider: ^4.2.1
  google_maps_flutter: ^2.6.0
  geocoding: ^2.2.0
  location: ^5.0.3
  google_maps_flutter_web: ^0.5.6+2
  image_picker: ^1.0.7
  readmore: ^2.2.0
  shimmer: ^3.0.0
  lottie: ^3.1.0
  flutter_otp_text_field: ^1.1.2+1
  syncfusion_flutter_calendar: ^25.1.42
  table_calendar: ^3.1.1
  geolocator: ^8.0.1 
  permission_handler: ^8.0.0
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  flutter_local_notifications: ^17.1.2
  rxdart: ^0.27.7
  android_alarm_manager_plus: ^4.0.3
  http_parser: ^4.0.2
  qr_flutter: ^4.1.0
  flutter_rating_bar: ^4.0.1
  easy_stepper: ^0.8.5
  camera: ^0.10.3
  file_picker: ^5.0.0
  win32: ^5.1.1
  qr_code_scanner: ^1.0.1
  mobile_scanner: ^5.1.1
  url_launcher: ^6.3.0
  modal_progress_hud_nsn: ^0.5.1
  flutter_pdfview: ^1.3.2
  google_places_flutter: ^2.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  freezed: ^2.4.7
  build_runner: ^2.4.8
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lotties/
    - assets/calender_bg/
    - assets/json/
    - assets/payment/

